from enum import StrEnum

class Stickers(StrEnum):
    S1 = "Sablay Smiski"
    S2 = "Lock In Smiski"
    S3 = "J*bless Smiski"
    S4 = "Sweater Smiski"
    M1 = "Grin 1"
    M2 = "Grin 2"
    M3 = "Nerdy Neko"
    M4 = "Ragebaited"
    M5 = "Tired"
    PC1 = "Python Enjoyer"
    PC2 = "C++ Enjoyer"
    R1 = "Iskeri Snupi"
    R2 = "CS Week Lights"
    R3 = "Shadow Monster"
    R4 = "Cassette"
    R5 = "Koket Dino"
    DC1 = "Flop"
    DC2 = "Homeless"
    DC3 = "Tara Nomi"
    DC4 = "Finger Bite"
    JI1 = "Absolute Cinema"
    JI2 = "Sleep"
    JI3 = "Low Cortisol"
    JI4 = "Holy Airball"
    JI5 = "Clown"
    JI6 = "Speed Please"
